### ISSUE TITLE
Space Symbols Draw With B-Standard Show Black Stripe

### ISSUE THREAD

**Issue by david-melendez** [missioncommand/old-mil-sym-java#63]
In the MIL-STD-2525C, the symbol frame for space symbols was modified to show a black stripe in the top of the frame to differentiate between space symbols and air symbols.  However, when drawing a space symbol with the standard set to B, the black stripe shows us like it's a C symbol.

**Comment by michael-spinelli** [comment]
While true, this helps more than it hinders.  It's also a good bit of work for 4 symbols that aren't used very much.  This will be a low priority.

**Comment by david-melendez** [comment]
I agree with your assessment.  However, this is what my testers are finding when testing my software.

**Comment by michael-spinelli** [comment]
Actually, that's a whole lot easier to fix than I thought it was.  I can get that done sooner.

**Comment by michael-spinelli** [comment]
fixed in release v0.1.21

**Comment by david-melendez** [comment]
This bug is not completely fixed.  It has only been fixed if the affiliation is FRIEND (or has FRIEND in it).  The black bar still appears for HOSTILE, NEUTRAL, UNKNOWN.
